-- Seed lingkungan pengembangan.
--
-- Data referensi yang dibutuhkan produksi — provinsi, paket, pembagian fitur,
-- dan tarif pesan Meta — tidak ada di sini. Semuanya masuk lewat migrasi
-- (20260815000005 dan 20260815000006), karena penagihan langganan dan siklus
-- tagihan membacanya di setiap lingkungan, bukan hanya saat pengembangan.
--
-- Berkas ini disediakan untuk data contoh yang hanya berguna saat mencoba
-- aplikasi secara lokal. Belum ada isinya: pemilik, kost, dan penyewa contoh
-- membutuhkan baris auth.users, yang lebih baik dibuat lewat alur pendaftaran
-- sungguhan daripada ditanam di sini.
